# Generated by Django 2.1.5 on 2019-08-28 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0003_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='gender',
            field=models.CharField(choices=[('FA', 'Female'), ('MA', 'Male')], max_length=120),
        ),
    ]
